# Generated by Django 5.2.9 on 2026-01-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='delivery_cart_items',
        ),
    ]
