# Generated by Django 5.2.9 on 2026-01-09 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.user'),
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
